spring:
  cloud:
    gateway:
      routes:
        - id: file
          uri: http://localhost:40000
          predicates:
            - Path=/file/**

        - id: auth
          uri: http://localhost:50000
          predicates:
            - Path=/auth/**

        - id: forum
          uri: http://localhost:60000
          predicates:
            - Path=/forum/**

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:1234@localhost:8761/eureka/